# -*- coding: utf-8 -*-
"""ListasYDiccionarios.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QbL5MPIAEGxMh7dTwBcQNMO9Bc4flPTS
"""



"""#Listas y diccionarios - Tipos de Datos Complejos

#Datos Simples:

- Cadenas - Strings
- Enteros - Int
- Decimales - float
- Booleano - True o False.

#Datos Complejos

Nos permiten almacenar multiples valores a la vez.

#Listas - Arrays

Es una colección ordenada de elementos, los cuales pueden modificarse, agregarse o eliminarse.

Ejemplo: Lista de compras.
Manzana, peras, pollo, bananos, cebolla.

#Diccionarios - Objetos

Es una colección de datos desordenada almacenada con clave y valor.
Ejemplo:

clave    valor
Paula: 3114589632
Pedro: 3647589632
Sebas: 3202569736
"""

#Lista

animales=["Perro", "Leopardo", "Tiburón"]
print(animales[1]) #Acceder a un elemento de la lista.

animales[2]="Rinoceronte" #Modificar un elemnto de la lista.
print(animales[2])

print(*animales) #Muestra toda la lista de animales. * quita los simbolos de la lista.

animales.append("León") #.append() me permite agregar un elemento a la lista, en la última posición.
print(*animales) #Siempre hay que poner el print para que salga en consola.

animales.pop() #Elimina el último objeto de la lista o agregando la posición.
print(*animales) #Siempre hay que poner el print para que salga en consola.

animales.remove("Perro") #.remove elimina con el nombre.
print(*animales)

print(len(animales)) #Longitud de la lista

#Diccionarios

contactos= {
    "Claudia":"3215689742",
    "Valery":"32569814534",
    "Juanjo":"65896542314"
}
print("El contacto de Claudia es: ", contactos["Claudia"]) #Llamo un elemento por medio de su clave

contactos["Maria"]="3205698741" #AGREGAR UN NUEVO ELEMENTO (CLAVE) AL DICCIONARIO.
print(contactos)

del contactos["Juanjo"] #Eliminar un elemento de un diccionario.
print(contactos)

tareas=["Estudiar inglés","Ejercicio", "Meditar","Cocinar","Sacar al perro"]
print(*tareas)

tareas[0]="Estudiar programación"
print(*tareas)

tareas.pop()
print(*tareas)

tareas.append("Adelantar trabajos")
print(*tareas)

productos={
    "Pollo":"10000",
    "Lechuga":"2000",
    "Pescado":"15000",
    "Tomate":"6000"

}

print(productos)

productos["Pollo"]="14000"
print(productos)

productos["Salchichón"]="5000"
print(productos)

del productos["Lechuga"]
print(*productos.keys(),*productos.values()) #keys-claves= te muestra todas las claves, values () muestre solo los valores.

contactos={
    "Pedro": {
        "Telefono":["312-548-6954", 3125896365],
        "Correo":["pedropedrope@gmail.com"],
        "Direccion":{
            "Calle":"calle 3a",
            "Ciudad":"Yumbo",
            "Barrio":"Bolívar"
        }
    },
    "Claudia":{
        "Telefono":["312-547-9632",3658963214],
        "Correo":"claudia2@gmail.com",
        "Direccion":{
            "Calle":"Calle 2b",
            "Barrio":"Uribe",
            "Ciudad":"Cali"
        }
    },
    "Sebastian":{
        "Telefono":["321-569-1236", 3212569874],
        "Correo":"sebas@gmail.com",
        "Direccion":{
            "Calle":"Carrera 4ta a",
            "Barrio":"Belalcazar",
            "Ciudad":"Yumbo"
        }
    }


}


contactos["Gabriela"]={ #AGREGAR CONTACTO
    "Telefono":["354-859-6369", 35478963258],
    "Correo": "gabi@gmail.com"
}
contactos["Pipe"]={
    "Telefono":["321-654-9875", 3697895262],
    "Correo": ["pipeflow@gmail.com", "pipelo@hotmail.com", "solorojo@yahoo.com"]
}
print(*contactos)

print("El telefono de Claudia es: ", contactos["Claudia"]["Telefono"])
print("El telefono de Pipe es: ", contactos["Pipe"]["Telefono"][0])

direccionSebas= contactos["Sebastian"]["Direccion"]["Ciudad"] #CUALQUIER VALOR SE PUEDE AGREGAR A UNA VARIABLE
print("La ciudad donde vive Sebastian es: ", direccionSebas)

telefonosGabi= contactos["Gabriela"]["Telefono"] #GUARDAR NUMEROS O VALORES EN UNA VARIABLE
print(telefonosGabi)

for telefono in telefonosGabi:
  print(telefono)

for i,telefono in enumerate(telefonosGabi, start=1): #Enumerate es una función que agrega un contador/indice a cada elemento, start le indicamos desde que número va a empezar a contar.
  print(f"Telefono {i}: ", telefono)

correoPipe= contactos["Pipe"]["Correo"]

for i, direcciones in enumerate(correoPipe, start=1):
  print(f"Correo número {i}: ", direcciones)

contactos["Pedro"]["Cumpleaños"]="20 de julio" #AGREGAR UNA CLAVE O CAMPO NUEVO A UN CONTACTO
print(contactos["Pedro"]["Cumpleaños"])

contactos["Pedro"]["Fecha de nacimiento"]=24, "de Agosto del", 1993
print(*contactos["Pedro"]["Fecha de nacimiento"])

yearBirth=contactos["Pedro"]["Fecha de nacimiento"][2]
yearAct=2024
if yearAct-yearBirth>=18:
  print("Pedro es mayor de edad.")
else:
  print("Pedro es menor de edad")

del contactos["Gabriela"] #ELIMINAR UN CONTACTO COMPLETO se puede agregar la posición que queremos eliminar agregandola en [0][1][2]...
print(*contactos)

contactos["Pipe"]["Correo"].remove("pipelo@hotmail.com")
print(*contactos["Pipe"]["Correo"])

